name: Build and publish application

on:
  push:
    branches:
      - main
    tags:
      - v*


jobs:
  build:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish frontend
        run: |-
          docker build --tag "djblackett/todo-go-frontend:${{ github.sha }}" ./frontend
          docker push "djblackett/todo-go-frontend:${{ github.sha }}"

      - name: Build and publish backend
        run: |-
          docker build --tag "djblackett/todo-go-backend:${{ github.sha }}" ./backend
          docker push "djblackett/todo-go-backend:${{ github.sha }}"

      - name: Build and publish broadcaster
        run: |-
          docker build --tag "djblackett/todo-go-broadcaster:${{ github.sha }}" ./broadcaster
          docker push "djblackett/todo-go-broadcaster:${{ github.sha }}"

  update_deployment_repo:
    name: update images in deployment repo
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout deployment repository
        uses: actions/checkout@v4
        with:
          repository: djblackett/k8s-todo-dep
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: deployment

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update images in deployment repo staging
        if: github.ref == 'refs/heads/main'
        run: |-
            cd deployment/manifests/overlays/staging
            kustomize edit set image todo-go-frontend="djblackett/frontend:$GITHUB_SHA" \
              todo-go-backend="djblackett/backend:$GITHUB_SHA" \
              todo-go-broadcaster="djblackett/broadcaster:$GITHUB_SHA"
            kustomize edit set namespace staging
            kustomize build .


      - name: Update images in deployment repo production
        if: startsWith(github.ref, 'refs/tags/')
        run: |-
            cd deployment/manifests/overlays/production
            kustomize edit set image todo-go-frontend="djblackett/frontend:$GITHUB_SHA" \
            todo-go-backend="djblackett/backend:$GITHUB_SHA" \
            todo-go-broadcaster="djblackett/broadcaster:$GITHUB_SHA"
            kustomize edit set namespace production
            kustomize build .

      - name: Commit and push changes
        env:
           GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          cd deployment
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update deployment images to ${{ github.sha }}"
          git push
